version: '3.3'

services:
  
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - ./DbScripts:/scripts
      - ./DbScripts/migration.sql:/docker-entrypoint-initdb.d/migration.sql
    ports:
      - "5432:5432"
    networks:
      - db
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - db
    restart: unless-stopped
    
  redis:
    container_name: redis
    image: redis:latest
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-redis}
    volumes:
        - redis:/data/redis
    ports:
        - "6379:6379"


networks:
  db:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  redis: